### ISSUE TITLE
Reason for using log scale sinkhorn algorithm

### ISSUE THREAD

**Issue by jihwanp** [Megvii-BaseDetection/OTA#17]
Hi Thanks for providing wonderful work!
I have a question about the sinkhorn distances implementation.

In the forward function of sinkhorn distances (below), you use log scale updating rule which is not same as original algorithm, and add v_t,u_t to update v_t+1,u_t+1. Whats the reason for that?
https://github.com/Megvii-BaseDetection/OTA/blob/2c85b4d0f9031396854aae969330dde2ab5eacbd/playground/detection/coco/ota.x101.dcnv2.fpn.coco.800size.1x/fcos.py#L693-L699

**Comment by utkutpcgl** [comment]
Thanks for the great contribution and thanks for asking @jihwanp. I am also curious about this. Could anyone find an answer to this issue?
