### ISSUE TITLE
Reproduction 

### ISSUE THREAD

**Issue by strongwolf** [Megvii-BaseDetection/OTA#2]
I changed nothing for the config file but only got 39.9 mAP when training res50 by myself. And I tested with your provided weight file and only got 31 mAP for res50 and 36 for res101.

**Comment by Joker316701882** [comment]
@strongwolf About the low mAP for our provided weight files, you are right, I'll work on it soon.

**Comment by Joker316701882** [comment]
@strongwolf About the low 39.9mAP for your own training. Did you use the latest version of cvpods?

**Comment by strongwolf** [comment]
> @strongwolf About the low 39.9mAP for your own training. Did you use the latest version of cvpods?

I used version 0.1.

**Comment by Joker316701882** [comment]
@strongwolf Hi, I re-trained an ota.res50 and got the following result:
![image](https://user-images.githubusercontent.com/18679821/117751514-d3c11280-b247-11eb-9a03-036dd1066b55.png)

So, I guess you need to update your cvpods to the latest version first, then check whether your COCO dataset is complete. Currently, I only upload the re-trained res50, the other models will come soon.
